### PR TITLE
Verkoopbijlages operations added

### LINKED ISSUE #23: VerkoopboekingBijlagesOperations is not available in the B2BClient

### PR DESCRIPTION
**Pull request by floris85**
Fixes #23 

This works, but is it good enough?

### CODE REVIEW

**Comment by swdevss** [comment]
Hi @floris85 ,

Almost there, I do have some remarks, could you please:

- Method naming: Remove WithParent from the method names, I think the parameters show that a parentId is required.
- Parameter order: let parentId precede child data, I think this is more natural, like:
```
UpdateAsync(Guid parentId, T dto)
DeleteAsync(Guid parentId, Guid id)
```
- Refactor the implicit coupling between resourceName and string.format. This is leaning on an convention, I would like to see this made explicit. 
My suggestion would be to combine a resourcename with a method that selects the Id from the parent and combine those two into a baseUrl like:
```
string GetParentUrl(Guid parentId) => $"{_resourceName}/{parentId}"
abstract Guid GetParentId(T dto};

public Task<Response> DeleteAsync(Guid id, Guid parentId) => ClientState.ExecuteDeleteAsync(GetParentUrl(parentId), id);

public Task<Response> DeleteAsync(T dto, Guid parentId) => ClientState.ExecuteDeleteAsync(GetParentUrl(GetParentId(dto)), dto.Id);
```

**Comment by floris85** [comment]
Hi @swdevss ,

I've changed the simple things (method naming + parameter order).

Refactoring the string.Format isn't done yet, as I'm not sure how to (yet).
Still thinking about it, any more help is appreciated!

**Comment by thombrink** [comment]
@floris85 I'm getting an exception when I try to add a bijlage.

```
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at SnelStart.B2B.Client.Operations.CrudOperationsWithParentBase`1.CreateAsync(Guid parentId, T dto)
```

is this expected?

**Comment by floris85** [comment]
so maybe the nuget package isn't up to date?
@henrybeensnelstart is this possible?

**Comment by henrybeen** [comment]
The version on NuGet was indeed one commit behind. There is no automated push (yet). 
@swdevss When you merge, mind giving me a quick heads-up, so I can push a new package out?

**Pull request merged**
